parameters:
  out: ""       # output root directory has to be specified
  amexclude: y  # arraymap is queried & existing samples are omitted
  randno: -1
  randpf: -1
  selpf: ""
  forcegpl: y   # default is updating this, in case new GSMs exist
  forcegsm: n
  forcegse: n
  probefiles: ".CEL,.gff,.txt,.tab,.tsv,.xls,.odt"
directories:
  logdir: logs
  georawdir: GEOraw
  geometadir: GEOmeta
  geotmpdir: 'GEOmeta/tmp'
  affyrawdir: affyRaw
  aromaroot: aroma
urls:
  geosoftlink: 'http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?form=text&acc='
cancer_matchwords:
  - cancer
  - leukemia
  - lymphoma
  - malignant
  - sarcoma
  - tumor
  - tumour
  - gliom
  - melanom
  - myelodyspl
  - myelom
  - cml
  - cll
  - refractory
  - mds
cancer_nomatch:
  - autism
  - autistic
  - GWAS
