platforms:
  excluded:
    - GPL570
    - GPL887
    - GPL885
    - GPL1390
    - GPL1708
    - GPL1998
    - GPL1999
    - GPL2012
    - GPL2013
    - GPL4611
    - GPL4910
    - GPL4911
    - GPL4912
    - GPL4913
    - GPL4914
    - GPL4915
    - GPL4916
    - GPL5790
    - GPL6444
    - GPL6445
    - GPL6446
    - GPL6447
    - GPL6448
    - GPL6449
    - GPL6450
    - GPL6254
    - GPL5790
    - GPL8490
    - GPL4126
    - GPL9816
    - GPL13821
    - GPL13534
    - GPL18053
  blessed:
    - GPL21558
    - GPL18602
    - GPL15793
    - GPL13270
    - GPL6804
    - GPL6801
    - GPL8226
    - GPL1266
    - GPL2641
    - GPL2004
    - GPL2005
    - GPL2014
    - GPL2015
    - GPL3718
    - GPL3720
    - GPL11157
    - GPL16131
    - GPL18637
  affyarrays:
    GPL6804: GenomeWideSNP_5
    GPL6801: GenomeWideSNP_6
    GPL8226: GenomeWideSNP_6
    GPL1266: Mapping10K_Xba131
    GPL2641: Mapping10K_Xba142
    GPL2004: Mapping50K_Hind240
    GPL2005: Mapping50K_Xba240
    GPL2014: Mapping50K_Hind240_pre_release
    GPL2015: Mapping50K_Xba240_pre_release
    GPL3718: Mapping250K_Nsp
    GPL3720: Mapping250K_Sty
    GPL11157: Cytogenetics_Array
    GPL16131: CytoScanHD_Array
    GPL18637: CytoScan750K_Array
    GPL21558: OncoScan_CNV
    GPL18602: OncoScan
    GPL15793: OncoScan_FFPE_Express_V2
    GPL13270: OncoScan_FFPE_Express
